### PR TITLE
skipping steps in voronoi using prediction

### PR DESCRIPTION
**Pull request by FxMorin**
The title says it all

### CODE REVIEW

**Comment by Titaniumtown** [comment]
I've found no issues with these optimizations personally. Would love to see numbers on actual performance though!

**Comment by Titaniumtown** [comment]
Why was this closed?

**Comment by 2No2Name** [comment]
Closed due to the contributor being banned from CaffeineMC projects

**Comment by Titaniumtown** [comment]
Oh?

**Comment by jellysquid3** [comment]
We believe that the user in question was involved in distributing targeted malware to other users outside of our projects. As a result, we don't feel confident about the intention of any patches they have submitted, nor do we want to risk accepting code that could act maliciously in an obfuscated manner.

**Pull request closed without merging**
