### PR TITLE
Update Gradle and Loom

### PR DESCRIPTION
**Pull request by DragonEggBedrockBreaking**
Similar to https://github.com/CaffeineMC/sodium-fabric/pull/630. Implements some changes https://github.com/CaffeineMC/sodium-fabric/commit/5545895d77f9a8f38bf936ba19a253abf36d92e7 (doesn't implement the main artifact tagging change, just a couple of the minor build.gradle deprecation things).

### CODE REVIEW

**Comment by tofiki** [comment]
Maybe update Loom to 0.7-SNAPSHOT instead of 0.6-SNAPSHOT as it speeds-up the build and it should have official gradle 7.0 support and should be stable, in my testing i haved no issues using it

**Comment by tofiki** [comment]
and remove jcenter() from 
> settings.gradle

**Comment by DragonEggBedrockBreaking** [comment]
> Maybe update Loom to 0.7-SNAPSHOT instead of 0.6-SNAPSHOT as it speeds-up the build and it should have official gradle 7.0 support and should be stable, in my testing i haved no issues using it

0.6-SNAPSHOT is the current recommended fabric-loom version (or was, until modmuss resigned). I will only do so if one of the Lithium devs asks me to as it is their repo/mod.

> and remove jcenter() from settings.gradle

done

**Comment by actuallyasmartname** [comment]
maybe update actions/setup-java to @v2? and maybe java 16?

**Comment by DragonEggBedrockBreaking** [comment]
> maybe update actions/setup-java to @v2?

didnt work, sorry

> and maybe java 16?

no

**Comment by actuallyasmartname** [comment]
> > maybe update actions/setup-java to @v2?
> 
> didnt work, sorry
> 
> > and maybe java 16?
> 
> no

ok

**Comment by actuallyasmartname** [comment]
> > maybe update actions/setup-java to @v2?
> 
> didnt work, sorry

Did you put the field distribution? you need that field.
Example is `with:`
`java-version: 15`
`distribution: adopt`

**Comment by DragonEggBedrockBreaking** [comment]
Erm, I’d rather not touch the workflows, so would you mind making your own PR for that? Plus, up to now, everything in this PR has been the same as in a Sodium PR that was merged, and I’d rather not diverge from that.

**Comment by actuallyasmartname** [comment]
> Erm, I’d rather not touch the workflows, so would you mind making your own PR for that? Plus, up to now, everything in this PR has been the same as in a Sodium PR that was merged, and I’d rather not diverge from that.

Ok.

**Comment by DragonEggBedrockBreaking** [comment]
Useless now that 1.17/dev has these features.

**Pull request closed without merging**
