### PR TITLE
change: Initially enable the palette container lock removal patch

### PR DESCRIPTION
**Pull request by maityyy**
As I wrote in the [discord](https://discordapp.com/channels/602796788608401408/648967810139029505/748258210128986132), it is absolutely safe. We are waiting for players' reports.

### CODE REVIEW

**Comment by maityyy** [comment]
Just as a reminder, all fixes are coming later.

**Comment by 2No2Name** [comment]
Why are you replacing Jelly's original implementation that overwrote the lock and unlock methods?

**Comment by maityyy** [comment]
I did this following the example of optimizing entity DataTracker so that the JVM sees empty methods and decides to completely remove this field.

**Comment by jellysquid3** [comment]
Implemented with 656ef5e9.

**Pull request closed without merging**
