### PR TITLE
update: Completely exclude Stream API from mob goal selection system

### PR DESCRIPTION
**Pull request by maityyy**
This small PR completely excludes the *Stream API* with lambdas from the `GoalSelector` class (`remove` method), which improves the game performance **with large counts of some mobs** (skeletons, zombies, cats and ocelots).

The changes in mspt are very difficult to see. I have used standard debugging using **F3+Alt** and have always noticed small performance gains. No problems were found in the behavior of the mobs.

**P. S.** Also, if I have made any stupid mistakes, please correct me. **English is not my native language.**

### CODE REVIEW

**Comment by maityyy** [comment]
I've updated the description to make it clearer what this PR does. Sorry for my mistakes.

**Review by 2No2Name — APPROVED** [review]
The code you are changing does not look like it is called often. The calls from cats/ocelots and skeleton horses are very rare. However Skeletons and Zombies being initialized might be relevant for some fast mob farms. I doubt that whatever improvement you noticed was from this patch though.

**Comment by maityyy** [comment]
Yes, it is rarely called. I also expect other mods to use it. I think we shouldn't leave it un-optimized when the whole goal selector has been rewritten. The function itself used slightly less memory in tests and was faster.

**Comment by maityyy** [comment]
It doesn't change anything on the Java versions above.

**Pull request closed without merging**
