### PR TITLE
Update Dependencies and Workflows

### PR DESCRIPTION
**Pull request by CanerKaraca23**

### CODE REVIEW

**Comment by 2No2Name** [comment]
Instead of updating binary files, please provide the commands used to update the files.

**Comment by CanerKaraca23** [comment]
> Instead of updating binary files, please provide the commands used to update the files.

For Gradle? Others need manual update.

`gradle wrapper --gradle-version 8.10`

**Comment by 2No2Name** [comment]
Thanks, merged manually

**Comment by CanerKaraca23** [comment]
> Thanks, merged manually

No problem, but you should also update gradlew and gradlew.bat

**Comment by 2No2Name** [comment]
Thanks. Had to rerun the gradle update

**Pull request closed without merging**
