### PR TITLE
Update to 1.20.5

### PR DESCRIPTION
**Pull request by DrexHD**
This draft PR is intended to track the progress of updating this mod to 1.20.5

### CODE REVIEW

**Comment by Boobies** [comment]
I don't think it's a good idea to rush porting. Give it a day or two for Yarn to catch up, otherwise you litter the code with magic names like `class_9172`. The first build typically mostly removes things that changed.

**Comment by DrexHD** [comment]
I am updating this mod for my own server. I will update mappings during next update or if any bugs arise. Before release candidates / official release everything will have yarn names.

**Comment by nickademas** [comment]
How can i download it?

**Comment by UltimatChamp** [comment]
> How can i download it?

https://github.com/DrexHD/lithium-fabric/actions/runs/8300824487/artifacts/1330506005

**Comment by KizGalaxy** [comment]
May I request an update to 24w14potato?

**Comment by DrexHD** [comment]
> May I request an update to 24w14potato?

I have done a lazy port yesterday and just [pushed that to my repo](https://github.com/DrexHD/lithium-fabric/tree/24w14potato).

**Pull request closed without merging**
