### PR TITLE
Updated loom to 0.6-SNAPSHOT (1.16)

### PR DESCRIPTION
**Pull request by krolik-exe**

### CODE REVIEW

**Comment by DragonEggBedrockBreaking** [comment]
This is already part of #224 and I have a closed PR that does this already, and I am willing to re-open if #224 is not merged.

**Comment by 2No2Name** [comment]
Is there any reaso to update to 0.6-SNAPSHOT in the 1.16 branch?

**Comment by DragonEggBedrockBreaking** [comment]
> Is there any reaso to update to 0.6-SNAPSHOT in the 1.16 branch?

Other than JDK 16, no, and for JDK 16, if someone is adamant on compiling the latest commit *and* using JDK 16, they should be able to realise to update the loom version.

**Comment by 2No2Name** [comment]
Updated it in the 1.17 dev branch. I will backport change this only if necessary

**Pull request closed without merging**
