### PR TITLE
Optimized explosion entity exposure calculations

### PR DESCRIPTION
**Pull request by crosby-moe**
## Overview  
This pull request comprises three optimizations:
- Optimize exposure raycasts by removing fluid handling, getting hit face, and other useless computations.
- Short-circuit exposure calculations on discarded entities.
- Remove duplicate `Explosion#getExposure` calls.

Since these optimizations specifically target entity-related explosion calculations, they have virtually no effect on single explosions. Chained explosions, however, see massive benefits due to the creation of dropped items & exp orbs which are then affected by the subsequent explosions.

I'm not particularly good at documentation, so suggestions are welcome.

## Benchmarks
~150% improvement in time spent exploding 4096 tnts.
Benchmarked using seed `-3199243952349285632` (randomly chosen) and 4096 tnt (`/fill ~1 ~-7 ~ ~16 ~8 ~15 tnt`)

Before:
9492 ms spent in `World.createExplosion()` [Spark profile](https://spark.lucko.me/f0gKvv0dY6)
before

After:
3832 ms spent in `World.createExplosion()` [Spark profile](https://spark.lucko.me/DzkUu3WLZ4)
after

### CODE REVIEW

**Comment by virophagesp** [comment]
i tested this, it works well

**Comment by 2No2Name** [comment]
Seems reasonable, will try to merge it soon

**Comment by virophagesp** [comment]
any updates?

**Comment by 2No2Name** [comment]
I found some issues with the PR, but I am fixing them myself. No need to take action. In case you are curious:

1. Use of static fields in fast_exposure.ExplosionMixin. (This would lead to issues with switching worlds, multithreading mods, or just having two explosions in the nether and the overworld at the same coordinates)
2. Sending the wrong velocity to dead players in fast_exposure.ExplosionMixin
3. Crashing when explosion is outside the world height
4. Inspiring me to move the optimization to all raycasts, not just explosions

**Comment by 2No2Name** [comment]
Rebased and included fixes / my own changes.

Thank you very much for your contribution @RacoonDog

**Pull request closed without merging**
