### PR TITLE
new: faster implementation of ScaleLayer

### PR DESCRIPTION
**Pull request by jaskarth**
This PR replaces ScaleLayer's sample method with a faster one that avoid sampling the surrounding biomes unless it is absolutely necessary, as ScaleLayer is the most used layer in the vanilla layer stack. This optimization is not that big when it comes to world generation, but it does have a noticeable impact when the locatebiome command is used. It also optimizes `x >> 1 << 1` into `x & ~1` for a bit smarter bitwise operation. There are no worldgen differences with this enabled.

Thanks to @gegy1000 and @Kroppeb for writing this :D

### CODE REVIEW

**Comment by Kroppeb** [comment]
It's `~1` which is `-2` and not `-1`

**Comment by jaskarth** [comment]
yeah sorry, typo 😅

**Review by jellysquid3 — APPROVED** [review]
LGTM. Do you have any numbers for performance that you could share?

**Comment by jaskarth** [comment]
Yeah. Unfortunately this isn't a super big performance improvement but when testing with a profiler (with `-XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints` enabled to avoid some of the safepoint bias) and the amount of profiler samples in `ScaleLayer#sample` decreased from 48 to 38 (26% improvement). It's not a massive speed boost but it should increase the performance of the biome generator overall.

**Review by jellysquid3 — APPROVED** [review]

**Pull request merged**
