### PR TITLE
Fix for #272

### LINKED ISSUE #272: Crash on rendering after installing litematica-printer
I have no idea except installation of litematica printer that can cause it. Without printer installed everything is fine. There was no other players around and only 1 litematic loaded and not visible in rendering frame (behind camera)

Hydrogen 0.3

Lithium 0.7.3

Sodium 0.3.0+build.5

```
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 8/19/21, 4:57 PM
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_265.method_1096(double, double, double)" because "shape" is null
	at me.jellysquid.mods.lithium.common.entity.movement.ChunkAwareBlockCollisionSweeper.getCollidedShape(ChunkAwareBlockCollisionSweeper.java:277)
	at me.jellysquid.mods.lithium.common.entity.movement.ChunkAwareBlockCollisionSweeper.getNextBlockCollision(ChunkAwareBlockCollisionSweeper.java:233)
	at me.jellysquid.mods.lithium.common.entity.movement.ChunkAwareBlockCollisionSweeper.getNextCollidedShape(ChunkAwareBlockCollisionSweeper.java:165)
	at me.jellysquid.mods.lithium.common.entity.LithiumEntityCollisions.doesBoxCollideWithBlocks(LithiumEntityCollisions.java:69)
	at net.minecraft.class_1941.method_8590(class_1941.java:536)
	at net.minecraft.class_1941.method_8587(class_1941.java:49)
	at net.minecraft.class_1297.method_20233(class_1297.java:1960)
	at net.minecraft.class_746.method_6007(class_746.java:691)
	at net.minecraft.class_1309.method_5773(class_1309.java:2346)
	at net.minecraft.class_1657.method_5773(class_1657.java:274)
	at net.minecraft.class_746.method_5773(class_746.java:210)
	at net.minecraft.class_638.method_18646(class_638.java:179)
	at net.minecraft.class_1937.method_18472(class_1937.java:483)
	at net.minecraft.class_638.method_32124(class_638.java:167)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:163)
	at net.minecraft.class_310.method_1574(class_310.java:1750)
	at net.minecraft.class_310.method_1523(class_310.java:1081)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.lithium.common.entity.movement.ChunkAwareBlockCollisionSweeper.getCollidedShape(ChunkAwareBlockCollisionSweeper.java:277)
	at me.jellysquid.mods.lithium.common.entity.movement.ChunkAwareBlockCollisionSweeper.getNextBlockCollision(ChunkAwareBlockCollisionSweeper.java:233)
	at me.jellysquid.mods.lithium.common.entity.movement.ChunkAwareBlockCollisionSweeper.getNextCollidedShape(ChunkAwareBlockCollisionSweeper.java:165)
	at me.jellysquid.mods.lithium.common.entity.LithiumEntityCollisions.doesBoxCollideWithBlocks(LithiumEntityCollisions.java:69)
	at net.minecraft.class_1941.method_8590(class_1941.java:536)
	at net.minecraft.class_1941.method_8587(class_1941.java:49)
	at net.minecraft.class_1297.method_20233(class_1297.java:1960)
	at net.minecraft.class_746.method_6007(class_746.java:691)
	at net.minecraft.class_1309.method_5773(class_1309.java:2346)
	at net.minecraft.class_1657.method_5773(class_1657.java:274)
	at net.minecraft.class_746.method_5773(class_746.java:210)
	at net.minecraft.class_638.method_18646(class_638.java:179)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_746)
	Entity ID: 1986181
	Entity Name: FlexCoral
	Entity's Exact location: CUT OUT
	Entity's Block location: World: CUT OUT
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:483)
	at net.minecraft.class_638.method_32124(class_638.java:167)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:163)

-- Affected level --
Details:
	All players: 1 total; [class_746['FlexCoral'/1986181, l='ClientLevel', CUT OUT]]
	Chunk stats: 1024, 169
	Level dimension: minecraft:overworld
	Level spawn location: World: (-48,64,144), Section: (at 0,0,0 in -3,4,9; chunk contains blocks -48,0,144 to -33,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 120785 game time, 67512785 day time
	Server brand: Airplane
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:747)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Programmer Art, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (amd64) version 5.4.0-81-generic
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 544982264 bytes (519 MiB) / 1509949440 bytes (1440 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 11
	Microarchitecture: whiskey Lake
	Frequency (GHz): 2.10
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: UHD Graphics 620 (Whiskey Lake)
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 256.00
	Graphics card #0 deviceId: 0x3ea0
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 10048.81
	Virtual memory used (MB): 6324.63
	Swap memory total (MB): 6144.00
	Swap memory used (MB): 388.50
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advancedchatcore: AdvancedChatCore 1.0.1-1.17.1
		advancedchatfilters: AdvancedChatFilters 1.0.0
		antighost: AntiGhost 1.17.1-fabric0.36.1-1.1.4
		autoclicker-fabric: Auto Clicker 1.17.1-1.2.1-build.9999
		baritone: Baritone 1.7.0
		bebooks: Better Enchanted Books 1.2.9
		betterpingdisplay: Better Ping Display 1.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.34
		com_github_hube12_seed: SEED master-SNAPSHOT
		crowdin-translate: CrowdinTranslate 1.3+1.17
		easiervillagertrading: EasierVillagerTrading 1.17.1-fabric0.36.1-1.5.4
		fabric: Fabric API 0.36.1+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d013
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea813
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446313
		fabric-command-api-v1: Fabric Command API (v1) 1.1.2+6cefd57713
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa13
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446313
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b446313
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31013
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57713
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446313
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c013
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa13
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57713
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446313
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612113
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446313
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e13
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446313
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446313
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa13
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446313
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.12+6cefd57713
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446313
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa13
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612113
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446313
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446313
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee13
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96913
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446313
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446313
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446313
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa13
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b446313
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab61213d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446313
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+6cefd57713
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b446313
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446313
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612113
		fabricloader: Fabric Loader 0.11.6
		gbfabrictools: GBfabrictools 1.3.4+1.17
		hydrogen: Hydrogen 0.3
		itemscroller: Item Scroller 0.15.0-dev.20210707.005506
		java: OpenJDK 64-Bit Server VM 16
		litematica: Litematica 0.0.0-dev.20210707.011234
		litematica_printer: Litematica Printer 2.0.0
		lithium: Lithium 0.7.3
		malilib: MaLiLib 0.10.0-dev.23
		meteor-client: Meteor Client 0.4.6
		minecraft: Minecraft 1.17.1
		modmenu: Mod Menu 2.0.4
		no_fog: No Fog 1.1.0+1.17.1
		sodium: Sodium 0.3.0+build.5
		xaerominimap: Xaero's Minimap 21.15.1
		xaeroworldmap: Xaero's World Map 1.16.1
	Launched Version: fabric-loader-0.11.6-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce MX230/PCIe/SSE2 GL version 3.2.0 NVIDIA 460.91.03, NVIDIA Corporation
	Window size: 1920x1033
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, programer_art, Fabric Mods
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz

-- Meteor Client --
Version: 0.4.6

[Combat]:
Anti Anvil (anti-anvil)
Auto Totem (auto-totem)
Criticals (criticals)
Hole Filler (hole-filler)
Kill Aura (kill-aura)

[Player]:
Anti Hunger (anti-hunger)
Auto Replenish (auto-replenish)
Middle Click Extra (middle-click-extra)
No Break Delay (no-break-delay)
Portals (portals)
Reach (reach)

[Movement]:
Anti Levitation (anti-levitation)
Entity Control (entity-control)
Entity Speed (entity-speed)
Jesus (jesus)
No Fall (no-fall)

[Render]:
Better Tooltips (better-tooltips)
Boss Stack (boss-stack)
Break Indicators (break-indicators)
Camera Tweaks (camera-tweaks)
Entity Owner (entity-owner)
Esp (esp)
Fullbright (fullbright)
HUD (HUD)
Logout Spots (logout-spots)
Nametags (nametags)
No Render (no-render)
Storage Esp (storage-esp)
Tracers (tracers)
Trajectories (trajectories)
Void Esp (void-esp)

[World]:
Anti Cactus (anti-cactus)
Auto Smelter (auto-smelter)
Enderman Look (enderman-look)
Stash Finder (stash-finder)

[Misc]:
Anti Packet Kick (anti-packet-kick)
Auto Reconnect (auto-reconnect)
Better Tab (better-tab)
Middle Click Friend (middle-click-friend)
Tps Sync (tps-sync)
Vanilla Spoof (vanilla-spoof)
```

### PR DESCRIPTION
**Pull request by OskHe**
Fixed https://github.com/CaffeineMC/lithium-fabric/issues/272

### CODE REVIEW

**Comment by 2No2Name** [comment]
How do we know that a null shape passed from some mod means that the shape should be replaced with an empty shape?
Did you find out why the shape is null in that location?

**Comment by OskHe** [comment]
A null shape means essentially no shape, and if there is no shape there can't be a collision. So null shape does the same like empty shape.
So the result of the function _getCollidedShape_ is still null (line 254) because _VoxelShapes.matchesAnywhere_ returns false.

**Comment by OskHe** [comment]
Another maby better way of solving it could be something like this:
> if (shape == null)
&nbsp;&nbsp;&nbsp;&nbsp;**return null;**

Here the **return null;** line is used because a null shape can't produce a collision.
This way it would not crash and the shapes are not modified like @2No2Name recommended.

**Comment by 2No2Name** [comment]
Implemented it myself

**Pull request closed without merging**
